-- Cleanup (optional, use with caution)
-- DROP TABLE IF EXISTS playlist_songs;
-- DROP TABLE IF EXISTS user_favorites;
-- DROP TABLE IF EXISTS playlists;
-- DROP TABLE IF EXISTS songs;
-- DROP TABLE IF EXISTS songbooks;
-- DROP TABLE IF EXISTS artists;
-- DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS academy;
-- DROP TABLE IF EXISTS app_settings;

-- Users
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'user',
  "lastActive" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  city TEXT,
  age INTEGER,
  "photoUrl" TEXT
);

-- Artists
CREATE TABLE IF NOT EXISTS artists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  "photoUrl" TEXT,
  biography TEXT
);

-- Songbooks
CREATE TABLE IF NOT EXISTS songbooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image TEXT,
  "pdfUrl" TEXT
);

-- Songs
CREATE TABLE IF NOT EXISTS songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  number INTEGER NOT NULL,
  content TEXT NOT NULL,
  "contentSimplified" TEXT,
  "contentLyrics" TEXT,
  "songbookId" BIGINT REFERENCES songbooks(id),
  "artistId" BIGINT REFERENCES artists(id),
  "isFavorite" BOOLEAN DEFAULT FALSE,
  "imageUrl" TEXT,
  "videoUrl" TEXT,
  "videoUrls" JSONB,
  "viewCount" INTEGER DEFAULT 0
);

-- User Favorites
CREATE TABLE IF NOT EXISTS user_favorites (
  "userId" BIGINT REFERENCES users(id),
  "songId" BIGINT REFERENCES songs(id),
  PRIMARY KEY("userId", "songId")
);

-- Playlists
CREATE TABLE IF NOT EXISTS playlists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  date TIMESTAMPTZ,
  "userId" BIGINT REFERENCES users(id),
  "shareId" TEXT UNIQUE NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Playlist Songs
CREATE TABLE IF NOT EXISTS playlist_songs (
  "playlistId" BIGINT REFERENCES playlists(id) ON DELETE CASCADE,
  "songId" BIGINT REFERENCES songs(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  PRIMARY KEY("playlistId", "songId")
);

-- Academy
CREATE TABLE IF NOT EXISTS academy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  "videoUrl" TEXT,
  content TEXT,
  type TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- App Settings
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- Default Settings
INSERT INTO app_settings (key, value) 
VALUES ('loading_image', 'https://i0.wp.com/schoenstatt.org.br/wp-content/uploads/2017/10/Mater-Admirabilis.jpg?fit=400%2C400&ssl=1')
ON CONFLICT (key) DO NOTHING;

INSERT INTO app_settings (key, value) 
VALUES ('app_icon', 'https://i0.wp.com/schoenstatt.org.br/wp-content/uploads/2017/10/Mater-Admirabilis.jpg?fit=400%2C400&ssl=1')
ON CONFLICT (key) DO NOTHING;
